-- ================================================================
-- PROMPTERCANTOR - CONFIGURAÇÃO DE SEGURANÇA E ARQUITETURA SAAS
-- Execute este script no SQL Editor do Supabase para liberar o acesso e
-- preparar a estrutura para múltiplos logins / SaaS com segurança.
-- ================================================================

-- 1. CRIAR OU AJUSTAR TABELA DE REPERTÓRIOS
CREATE TABLE IF NOT EXISTS repertoires (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    name TEXT NOT NULL,
    source TEXT DEFAULT 'manual',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CRIAR OU AJUSTAR TABELA DE MÚSICAS
CREATE TABLE IF NOT EXISTS songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    repertoire_id BIGINT REFERENCES repertoires(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    key TEXT DEFAULT '',
    original_key TEXT DEFAULT '',
    rhythm TEXT DEFAULT '',
    artist TEXT DEFAULT '',
    composer TEXT DEFAULT '',
    youtube_url TEXT DEFAULT '',
    youtube_id TEXT DEFAULT '',
    content TEXT DEFAULT '',
    track_number INT DEFAULT NULL,
    "order" INT DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir coluna rhythm se a tabela já existia
ALTER TABLE songs ADD COLUMN IF NOT EXISTS rhythm TEXT DEFAULT '';

-- 3. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE repertoires ENABLE ROW LEVEL SECURITY;
ALTER TABLE songs ENABLE ROW LEVEL SECURITY;

-- 4. REMOVER POLÍTICAS ANTIGAS (SE EXISTIREM)
DROP POLICY IF EXISTS "Public access to repertoires" ON repertoires;
DROP POLICY IF EXISTS "Public access to songs" ON songs;
DROP POLICY IF EXISTS "User access to repertoires" ON repertoires;
DROP POLICY IF EXISTS "User access to songs" ON songs;
DROP POLICY IF EXISTS "Allow anon and auth full access to repertoires" ON repertoires;
DROP POLICY IF EXISTS "Allow anon and auth full access to songs" ON songs;

-- 5. POLÍTICA ATUAL DE TRANSIÇÃO (Permite acesso anônimo/público até ativar o login)
CREATE POLICY "Allow anon and auth full access to repertoires" ON repertoires
    FOR ALL
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow anon and auth full access to songs" ON songs
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- ================================================================
-- NOTA PARA MODO SAAS COM LOGIN (MÚLTIPLOS USUÁRIOS):
-- Quando ativarmos a tela de Login, trocaremos as políticas 5 pelas regras abaixo:
-- 
-- CREATE POLICY "User access to repertoires" ON repertoires
--     FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
-- 
-- CREATE POLICY "User access to songs" ON songs
--     FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
-- ================================================================
